---
language: python
python: "3.6"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - gem install travis

before_script:
  - docker run --name xenial -d codeyourinfra/python3:xenial
  - docker run --name bionic -d codeyourinfra/python3:bionic
  - docker run --name alpine -d codeyourinfra/python3:alpine

script:
  - ansible-galaxy install -r requirements.yml -p tests/roles
  - ansible-playbook tests/test.yml -i tests/inventory

after_script:
  - docker stop xenial bionic alpine
  - docker rm xenial bionic alpine

after_success:
  - curl -LO https://raw.github.com/stephanmg/travis-dependent-builds/master/trigger.sh
  - chmod +x trigger.sh
  - ./trigger.sh codeyourinfra jenkins master $TRAVIS_GITHUB_TOKEN
  - ./trigger.sh codeyourinfra maven master $TRAVIS_GITHUB_TOKEN

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/