---
language: python
python: "3.6"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible

before_script:
  - docker run --name xenial -d codeyourinfra/python3:xenial
  - docker run --name bionic -d codeyourinfra/python3:bionic

script:
  - ansible-playbook tests/test.yml -i tests/inventory

after_script:
  - docker stop xenial bionic
  - docker rm xenial bionic

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/