---
language: python
python: "2.7"

sudo: required

services:
  - docker

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  - docker run --name xenial -d codeyourinfra/python3:xenial
  - docker run --name bionic -d codeyourinfra/python3:bionic
  - ansible-playbook tests/test.yml -i tests/inventory
  - docker stop xenial bionic
  - docker rm xenial bionic

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/